# Generated by Django 5.1a1 on 2024-06-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0002_auto_20240528_1604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="letting",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
