name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build_job:
    stage: build
    image: docker:19.03.12
    services:
      - docker:19.03.12-dind
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      - name: Récupération du hash du commit
        run: COMMIT_HASH=$(git rev-parse --short HEAD)
      - name: Construction de l'image Docker
        run: |
          docker build --build-arg SENTRY=$SENTRY -t cicd:$COMMIT_HASH .
          docker tag cicd:$COMMIT_HASH cicd:$COMMIT_HASH
