name: CI


on:
  push:
    branches:
      - '*'  # Exécute la CI pour toutes les branches

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest

      - name: Verify server starts
        run: |
          nohup python manage.py runserver & sleep 5;
          curl -f http://127.0.0.1:8000 || (echo "Server failed to start" && exit 1)

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract commit hash
        id: get_commit
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Construction de l'image Docker
        run: |
          docker build --build-arg SENTRY=${{ secrets.SENTRY }} -t cicd .
          docker tag cicd:latest ${{ secrets.DOCKER_USERNAME }}/cicd:${{ env.COMMIT_HASH }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd:${{ env.COMMIT_HASH }}
