name: CI

on:
  push:
    branches:
      - '*'

stages:
  - build
  - test

jobs:
  build_job:
    stage: build
    image: docker:19.03.12
    services:
      - docker:19.03.12-dind
    script:
      - COMMIT_HASH=$(git rev-parse --short HEAD)
      - docker build --build-arg SENTRY=$SENTRY -t cicd:$COMMIT_HASH .
      - docker tag cicd:$COMMIT_HASH cicd:$COMMIT_HASH
