name: CICD


on:
  push:
    branches:
      - master

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check migrations are up to date
        run: |
          python manage.py makemigrations --check --dry-run

      - name: Verify code with Flake8
        run: |
          pip install flake8
          flake8 .

      - name: Run unit tests with coverage
        run: |
          pytest --cov=.

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract commit hash
        id: get_commit
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Construction de l'image Docker
        run: |
          docker build --build-arg SENTRY=${{ secrets.SENTRY }} -t cicd .
          docker tag cicd:latest ${{ secrets.DOCKER_USERNAME }}/cicd:${{ env.COMMIT_HASH }}
          docker tag cicd:latest ${{ secrets.DOCKER_USERNAME }}/cicd:latest

      - name: Push Docker image

        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd:${{ env.COMMIT_HASH }}
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd:latest
